<?php
/**
 * Copyright © Thuiswinkel.org. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="mm-block-bewust_bezorgd">
    <p>
        <strong>Bewust Bezorgd – de groene bezorgoptie in jouw winkelmandje</strong>
        <br>
        Wil je jouw webshop verduurzamen én bewuste consumenten aantrekken? Voeg de Bewust Bezorgd plugin toe! Per bestelling laat Bewust Bezorgd zien welke bezorgoptie de groene optie is.
        Zo help je jouw klanten duurzamer te shoppen en bovendien krijg je zelf inzicht in de CO2 impact van al jouw pakketverzendingen.
        <br>
        <span class="phoneline">
            Heb je vragen? Chat met ons via <a href="https://www.thuiswinkel.org/" class="web">www.thuiswinkel.org</a> of bel <a href="tel:0318 64 85 75" class="phone">0318 64 85 75</a>.
        </span>
    </p>
</div>