<?php

// @codingStandardsIgnoreFile

/** @var Thuiswinkel\BewustBezorgd\Block\Adminhtml\System\Config\ValidatePermissions $block */
?>
<script>
require([
    'Magento_Ui/js/modal/alert',
    'mage/translate',
    'prototype'
], function(alert, $t) {

//<![CDATA[
    function validatePermissions() {
        var validationMessage = $('validation_result');

        params = {
            apiShopId: $('<?= $block->escapeJs($block->getApiShopIdField()) ?>').value,
            apiPassword: $('<?= $block->escapeJs($block->getApiPasswordField()) ?>').value
        };

        new Ajax.Request('<?= $block->escapeJs($block->escapeUrl($block->getAjaxUrl())) ?>', {
            parameters: params,
            onSuccess: function(response) {
                let message = '<?= $block->escapeJs(
    $block->escapeHtml(__('Error during credentials verification.'))
) ?>';
                try {
                    if (response.responseText.isJSON()) {
                        response = response.responseText.evalJSON();
                        message = response.message;
                    }
                    alert({
                        title: response.valid ? $t('Success') : $t('Error'),
                        content: message
                    });
                } catch (e) {
                    alert({
                        title: $t('Error'),
                        content: $t('Something went wrong during validation.')
                    });
                }
            }
        });
    }

    window.validatePermissions = validatePermissions;
//]]>

});
</script>
<div class="actions actions-validate-permissions">
    <div id="validation_result" class="message-validation hidden"></div>
    <button onclick="javascript:validatePermissions(); return false;"
            class="action-validate-permissions"
            type="button"
            id="<?= $block->escapeHtmlAttr($block->getHtmlId()) ?>">
        <span><?= $block->escapeHtml($block->getButtonLabel()) ?></span>
    </button>
</div>
